// WARNING: do not edit this file, it's automatically generated by GenerateElementMapPlugin

declare global {
  interface HTMLElementTagNameMap {
    "mdn-about-tabs": import("../components/about-tabs/element.js").MDNAboutTabs;
    "mdn-about-team-member": import("../components/about-team-member/element.js").MDNAboutTeamMember;
    "mdn-button": import("../components/button/element.js").MDNButton;
    "mdn-code-example": import("../components/code-example/element.js").MDNCodeExample;
    "mdn-color-theme": import("../components/color-theme/element.js").MDNColorTheme;
    "mdn-compat-table": import("../components/compat-table/element.js").MDNCompatTable;
    "mdn-compat-table-lazy": import("../components/compat-table-lazy/element.js").MDNCompatTableLazy;
    "mdn-content-feedback": import("../components/content-feedback/element.js").MDNContentFeedback;
    "mdn-contributor-list": import("../components/contributor-list/element.js").MDNContributorList;
    "mdn-copy-button": import("../components/copy-button/element.js").MDNCopyButton;
    "mdn-dropdown": import("../components/dropdown/element.js").MDNDropdown;
    "mdn-image-history": import("../components/image-history/element.js").MDNImageHistory;
    "mdn-interactive-example": import("../components/interactive-example/element.js").MDNInteractiveExample;
    "mdn-issues-table": import("../components/issues-table/element.js").MDNIssuesTable;
    "mdn-ix-tab": import("../components/ix-tab/element.js").MDNIXTab;
    "mdn-ix-tab-panel": import("../components/ix-tab-panel/element.js").MDNIXTabPanel;
    "mdn-ix-tab-wrapper": import("../components/ix-tab-wrapper/element.js").MDNIXTabWrapper;
    "mdn-language-switcher": import("../components/language-switcher/element.js").MDNLanguageSwitcher;
    "mdn-live-sample-result": import("../components/live-sample-result/element.js").MDNLiveSampleResult;
    "mdn-observatory-comparison-table": import("../components/observatory-comparison-table/element.js").MDNObservatoryComparisonTable;
    "mdn-observatory-form": import("../components/observatory-form/element.js").MDNObservatoryForm;
    "mdn-observatory-human-duration": import("../components/observatory-human-duration/element.js").MDNObservatoryHumanDuration;
    "mdn-observatory-rescan-button": import("../components/observatory-rescan-button/element.js").MDNObservatoryRescanButton;
    "mdn-observatory-results": import("../components/observatory-results/element.js").MDNObservatoryResults;
    "mdn-placement-bottom": import("../components/placement-bottom/element.js").MDNPlacementBottom;
    "mdn-placement-hp-main": import("../components/placement-hp-main/element.js").MDNPlacementHpMain;
    "mdn-placement-no": import("../components/placement-no/element.js").MDNPlacementNo;
    "mdn-placement-note": import("../components/placement-note/element.js").MDNPlacementNote;
    "mdn-placement-sidebar": import("../components/placement-sidebar/element.js").MDNPlacementSidebar;
    "mdn-placement-top": import("../components/placement-top/element.js").MDNPlacementTop;
    "mdn-play-console": import("../components/play-console/element.js").MDNPlayConsole;
    "mdn-play-controller": import("../components/play-controller/element.js").MDNPlayController;
    "mdn-play-editor": import("../components/play-editor/element.js").MDNPlayEditor;
    "mdn-play-runner": import("../components/play-runner/element.js").MDNPlayRunner;
    "mdn-playground": import("../components/playground/element.js").MDNPlayground;
    "mdn-progress-bar": import("../components/progress-bar/element.js").MDNProgressBar;
    "mdn-search-modal": import("../components/search-modal/element.js").MDNSearchModal;
    "mdn-sidebar-filter": import("../components/sidebar-filter/element.js").MDNSidebarFilter;
    "mdn-site-search": import("../components/site-search/element.js").MDNSiteSearch;
  }
}

export {};
