// WARNING: do not edit this file, it's automatically generated by GenerateElementMapPlugin

declare global {
  interface HTMLElementTagNameMap {
    "mdn-button": import("../components/button/element.js").MDNButton;
    "mdn-code-example": import("../components/code-example/element.js").MDNCodeExample;
    "mdn-search-modal": import("../components/search-modal/element.js").MDNSearchModal;
  }
}

export {};
