# WARNING: do not edit this file, it's automatically generated by ExtractL10nPlugin.
# If you need to manually add strings, do so in ./locales/en-US.ftl. See ./README.md for more details.

article-footer-last-modified = This page was last modified on <time data-l10n-name="date">{ $date }</time> by <a data-l10n-name="contributors">MDN contributors</a>.
article-footer-source-title = Folder: { $folder } (Opens in a new tab)
baseline-asterisk = Some parts of this feature may have varying levels of support.
baseline-high-extra = This feature is well established and works across many devices and browser versions. It’s been available across browsers since { $date }.
baseline-low-extra = Since { $date }, this feature works across the latest devices and browser versions. This feature might not work in older devices or browsers.
baseline-not-extra = This feature is not Baseline because it does not work in some of the most widely-used browsers.
baseline-supported-in = Supported in { $browsers }
baseline-unsupported-in = Not widely supported in { $browsers }
baseline-supported-and-unsupported-in = Supported in { $supported }, but not widely supported in { $unsupported }
homepage-hero-title = Resources for Developers,<br> by Developers
homepage-hero-description = Documenting <a data-l10n-name="css">CSS</a>, <a data-l10n-name="html">HTML</a>, and <a data-l10n-name="js">JavaScript</a>, since 2005.
not-found-title = Page not found
not-found-description = Sorry, the page <code data-l10n-name="url">{ $url }</code> could not be found.
not-found-fallback-english = <strong data-l10n-name="strong">Good news:</strong> The page you requested exists in <em data-l10n-name="em">English</em>.
not-found-fallback-search = The page you requested doesn't exist, but you could try a site search for:
not-found-back = Go back to the home page
reference-toc-header = In this article
footer-mofo = Visit <a data-l10n-name="moco">Mozilla Corporation’s</a> not-for-profit parent, the <a data-l10n-name="mofo">Mozilla Foundation</a>.
footer-copyright = Portions of this content are ©1998–{ $year } by individual mozilla.org contributors. Content available under <a data-l10n-name="cc">a Creative Commons license</a>.
search-modal-site-search = Site search for <em>{ $query }</em>
site-search-search-stats = Found { $results } documents.
site-search-suggestion-matches =
    { $relation ->
        [gt]
            more than { $matches ->
                [one] { $matches } match
               *[other] { $matches } matches
            }
       *[eq]
            { $matches ->
                [one] { $matches } match
               *[other] { $matches } matches
            }
    }
site-search-suggestions-text = Did you mean:
blog-time-to-read =
    { $minutes ->
        [one] { $minutes } minute read
       *[other] { $minutes } minutes read
    }
blog-post-not-found = Blog post not found.
blog-previous = Previous post
blog-next = Next post
-brand-name-obs = HTTP Observatory
obs-report = Report
obs-title = { -brand-name-obs }
obs-landing-intro = Launched in 2016, the { -brand-name-obs } enhances web security by analyzing compliance with best security practices. It has provided insights to over 6.9 million websites through 47 million scans.
obs-assessment = Developed by Mozilla, the { -brand-name-obs } performs an in-depth assessment of a site’s HTTP headers and other key security configurations.
obs-scanning = Its automated scanning process provides developers and website administrators with detailed, actionable feedback, focusing on identifying and addressing potential security vulnerabilities.
obs-security = The tool is instrumental in helping developers and website administrators strengthen their sites against common security threats in a constantly advancing digital environment.
obs-mdn = The { -brand-name-obs } provides effective security insights, guided by Mozilla's expertise and commitment to a safer and more secure internet and based on well-established trends and guidelines.
compat-loading = Loading…
compat-browser-version-date = { $browser } { $version } – Released { $date }
compat-browser-version-released = Released { $date }
compat-link-report-issue = Report problems with this compatibility data
compat-link-report-issue-title = Report an issue with this compatibility data
compat-link-report-missing-title = Report missing compatibility data
compat-link-report-missing = Report this issue
compat-link-source = View data on GitHub
compat-link-source-title = File: { $filename }
compat-deprecated = Deprecated
compat-experimental = Experimental
compat-nonstandard = Non-standard
compat-no = No
compat-support-full = Full support
compat-support-partial = Partial support
compat-support-no = No support
compat-support-unknown = Support unknown
compat-support-preview = Preview browser support
compat-support-prefix = Implemented with the vendor prefix: { $prefix }
compat-support-altname = Alternate name: { $altname }
compat-support-removed = Removed in { $version } and later
compat-support-see-impl-url = See <a data-l10n-name="impl_url">{ $label }</a>
compat-support-flags =
    { NUMBER($has_added) ->
        [one] From version { $version_added }
       *[other] { "" }
    }{ $has_last ->
        [one]
            { NUMBER($has_added) ->
               *[zero] Until { $versionLast } users
                [one] { " " }until { $versionLast } users
            }
       *[zero]
            { NUMBER($has_added) ->
               *[zero] Users
                [one] { " " }users
            }
    }
    { " " }must explicitly set the <code data-l10n-name="name">{ $flag_name }</code>{ " " }
    { $flag_type ->
       *[preference] preference
        [runtime_flag] runtime flag
    }{ NUMBER($has_value) ->
        [one] { " " }to <code data-l10n-name="value">{ $flag_value }</code>
       *[other] { "" }
    }{ "." }
    { $flag_type ->
        [preference] To change preferences in { $browser_name }, visit { $browser_pref_url }.
       *[other] { "" }
    }
compat-legend = Legend
compat-legend-tip = Tip: you can click/tap on a cell for more information.
compat-legend-yes = { compat-support-full }
compat-legend-partial = { compat-support-partial }
compat-legend-preview = In development. Supported in a pre-release version.
compat-legend-no = { compat-support-no }
compat-legend-unknown = Compatibility unknown
compat-legend-experimental = { compat-experimental }. Expect behavior to change in the future.
compat-legend-nonstandard = { compat-nonstandard }. Check cross-browser support before using.
compat-legend-deprecated = { compat-deprecated }. Not for use in new websites.
compat-legend-footnote = See implementation notes.
compat-legend-disabled = User must explicitly enable this feature.
compat-legend-altname = Uses a non-standard name.
compat-legend-prefix = Requires a vendor prefix or different name for use.
compat-legend-more = Has more compatibility info.
placement-note = Ad
placement-no = Don't want to see ads?
pagination-next = Next page
pagination-prev = Previous page
pagination-current = Current page
pagination-goto = Go to page { $page }
logout = Sign out
login = Log in
settings = My settings
example-play-button-label = Play
example-play-button-title = Run example in MDN Playground (opens in new tab)
skip-to-main-content-kp9i = Skip to main content
skip-to-search-17gk = Skip to search
learn-how-to-contribute-g07f = Learn how to contribute
view-this-page-on-github-1hde = View this page on GitHub
this-will-take-you-to-github-to-9hic = This will take you to GitHub to file a new issue.
report-a-problem-with-this-conte-1mwa = Report a problem with this content
baseline-cross-148l = Baseline Cross
baseline-check-14gc = Baseline Check
limited-availability-13ek = Limited availability
baseline-1gj8 = Baseline
widely-available-1u5i = Widely available
newly-available-d6a7 = Newly available
check-2xey = check
cross-2xgq = cross
learn-more-1o3l = Learn more
see-full-compatibility-omsy = See full compatibility
report-feedback-13qx = Report feedback
blog-previous = Previous Post
blog-next = Next post
blog-it-better-zfyf = Blog it better
reference-toc-header = In this article
blog-post-not-found = Blog post not found
save-in-collection-2sdd = Save in collection
remove-1ih9 = Remove
save-yjzj = Save
add-to-collection-1p4p = Add to collection
collection-1y5l = Collection:
saved-articles-mule = Saved articles
new-collection-18z4 = New collection
name-3kiu = Name:
note-3khl = Note:
saving-1bub = Saving…
cancel-18x3 = Cancel
deleting-1rvl = Deleting…
delete-16wm = Delete
theme-default = OS default
light-3loo = Light
dark-yjkq = Dark
switch-color-theme-10hx = Switch color theme
theme-3rth = Theme
compat-link-report-issue-title = Report an issue with this compatibility data
compat-link-report-issue = Report problems with this compatibility data
compat-link-source = View data on GitHub
compat-experimental = Experimental
compat-deprecated = Experimental
compat-nonstandard = Non-standard
compat-support-partial = Partial support
compat-support-preview = Preview support
compat-support-full = Full support
compat-support-no = No support
compat-support-unknown = Support unknown
compat-yes = Yes
compat-partial = Partial
compat-no = No
compat-legend = Legend
compat-legend-tip = Tip: you can click/tap on a cell for more information.
compat-link-report-missing-title = Report missing compatibility data
compat-link-report-missing = Report this issue
compat-loading = Loading…
content-feedback-question = Was this page helpful to you?
yes-376p = Yes
no-3hna = No
content-feedback-reason = Why was this page not helpful to you?
submit-1ivp = Submit
content-feedback-thanks = Thank you for your feedback!
want-to-be-part-of-the-journey-tj68 = Want to be part of the journey?
our-constant-quest-for-innovatio-o2x9 = Our constant quest for innovation starts here, with you. Every part of MDN (docs, demos and the site itself) springs from our incredible open community of developers. Please join us!
contributor-profile-h45r = Contributor profile
copied-18w5 = Copied
copy-failed-aec2 = Copy failed!
copy-yjn7 = Copy
mdn-on-github-ha0a = MDN on GitHub
mdn-on-bluesky-15oy = MDN on Bluesky
mdn-on-x-1ht5 = MDN on X
mdn-on-mastodon-gz9n = MDN on Mastodon
mdn-blog-rss-feed-xx1x = MDN blog RSS feed
mdn-3769 = MDN
about-3ebm = About
blog-yjmm = Blog
mozilla-careers-6a7r = Mozilla careers
advertise-with-us-1m98 = Advertise with us
mdn-plus-1hsl = MDN Plus
product-help-twv0 = Product help
contribute-ur20 = Contribute
mdn-community-1a2k = MDN Community
community-resources-175y = Community resources
writing-guidelines-nkte = Writing guidelines
mdn-discord-1d86 = MDN Discord
developers-m0ik = Developers
web-technologies-1khu = Web technologies
learn-web-development-psay = Learn web development
guides-16q9 = Guides
tutorials-1phf = Tutorials
glossary-1klw = Glossary
hacks-blog-18lu = Hacks blog
website-privacy-notice-19vo = Website Privacy Notice
cookies-1oga = Cookies
legal-3lxp = Legal
community-participation-guidelin-ir07 = Community Participation Guidelines
mdn-logo-1ht4 = MDN logo
footer-tagline = Your blueprint for a better internet.
mozilla-logo-ga04 = Mozilla logo
generic-toc__header = In this article
featured-articles-y0ni = Featured articles
latest-news-1tvp = Latest news
recent-contributions-kik0 = Recent contributions
contributor-spotlight-1qnv = Contributor Spotlight
get-involved-10ku = Get involved
search-the-site-13uv = Search the site
search-1j74 = Search
reset-3swj = Reset
value-select-873f = Value select
the-current-value-is-not-support-1m7m = The current value is not supported by your browser.
run-example-and-show-console-ou-14k0 = Run example, and show console output
run-376m = Run
reset-example-and-clear-console-whty = Reset example, and clear console output
console-output-q07x = Console output
output-1bw1 = Output
remember-language-8ut5 = Remember language
enable-this-setting-to-always-sw-1ah2 = Enable this setting to always switch to the current language when available. (Click to learn more.)
login-3lw0 = Login
obs-about-title = About the HTTP Observatory
read-our-faq-rafe = Read our FAQ
report-feedback-1e4t = Report Feedback
rescan-1igp = Rescan
wait-a-minute-to-rescan-8uvn = Wait a minute to rescan
faq-3765 = FAQ
pagination-5qfe = Pagination
do-you-really-want-to-clear-ever-192d = Do you really want to clear everything?
do-you-really-want-to-revert-you-1o83 = Do you really want to revert your changes?
playground-gj6l = Playground
format-15w4 = Format
share-3tz9 = Share
clear-3ill = Clear
console-1ofu = Console
share-markdown-1fv6 = Share Markdown
copy-markdown-to-clipboard-clet = Copy markdown to clipboard
share-your-code-via-permalink-oor0 = Share your code via Permalink
copy-to-clipboard-8ok2 = Copy to clipboard
create-link-1n16 = Create link
loading-search-index-19qe = Loading search index…
exit-search-1yon = Exit search
filter-sidebar-1v9u = Filter sidebar
filter-15rf = Filter
clear-filter-input-ud9f = Clear filter input
previous-17il = Previous
next-yjpj = Next
site-search-suggestions-text = Did you mean…
searching-1q50 = Searching…
language-1s1g = Language
both-yjmi = Both
this-feature-does-not-appear-to-lkgx = This feature does not appear to be defined in any specification.
specification-etos = Specification
hide-this-survey-1c9b = Hide this survey
toggle-sidebar-hffq = Toggle sidebar
user-yjrj = User
open-in-editor-5g3t = Open in editor
view-on-mdn-1nup = View on MDN
