name: Update menu

on:
  workflow_dispatch:

  schedule:
    - cron: "30 4 * * 1-5"

permissions: {} # No GITHUB_TOKEN permissions, because we use MDN_BOT_PAT instead.

jobs:
  update:
    if: github.repository == 'mdn/fred'
    name: Update missing docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
          ref: main

      - name: Setup Node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version-file: .nvmrc
          package-manager-cache: false

      - name: Install
        run: npm ci
        env:
          # Increase GitHub API limit.
          GITHUB_TOKEN: ${{ github.token }}

      - name: Update tabs
        run: node components/menu/update-tabs.js

      - name: Update missing docs
        run: node components/menu/update-missing-docs.js

      - name: Format
        run: npx prettier -w components/menu/*.json

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          token: ${{ secrets.MDN_BOT_PAT }}
          commit-message: "chore(menu): update menu entries"
          author: mdn-bot <108879845+mdn-bot@users.noreply.github.com>
          committer: mdn-bot <108879845+mdn-bot@users.noreply.github.com>
          signoff: false
          branch: update-menu
          delete-branch: true
          add-paths: components/menu/*.json
          title: "chore(menu): update menu entries"
          body: (This PR was generated by [this run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}) of the [`${{ github.workflow }}`](https://github.com/${{ github.repository }}/blob/${{ github.ref_name }}/.github/workflows/update-menu.yml) workflow.)
          draft: false
